export default function sout(): {
    debug: boolean;
    log: typeof log;
    slog: typeof slog;
    print: typeof print;
    info: typeof info;
    success: typeof success;
    warn: typeof warn;
    unsure: typeof unsure;
    ops: typeof ops;
    error: typeof error;
    good: typeof good;
    wink: typeof wink;
    bad: typeof bad;
    tracker: typeof tracker;
    table: typeof table;
    showAll: () => void;
};
export declare function bad(m: any, head?: any): void;
export declare function error(m: any, head?: any): void;
export declare function good(m: any, head?: any): void;
export declare function info(m: any, head?: any): void;
export declare function log(m: any): void;
export declare function ops(m: any, head?: any): void;
export declare function print(m: any, head?: any): void;
export declare function slog(m: any): void;
export declare function success(m: any, head?: any): void;
export declare function table(m: any): void;
export declare function tracker(m: any, ...additionalMessages: any[]): void;
export declare function unsure(m: any, head?: any): void;
export declare function warn(m: any, head?: any): void;
export declare function wink(m: any, head?: any): void;
