export declare var Filetree: {
    createDocWithMd: typeof 通过markdown创建文档;
    removeDoc: typeof 删除思源文档;
    renameDoc: typeof 重命名思源文档;
    moveDoc: typeof 移动思源文档;
    getHPathByPath: typeof 根据思源路径获取人类可读路径;
    getHPathByID: typeof 根据块ID查询文档人类可读完整路径;
    listDocsByPath: typeof 列出指定路径下文档;
    getDoc: typeof 以id获取文档内容;
    searchDocs: typeof 以关键词搜索文档;
};
declare function 重命名思源文档(笔记本id: any, 文档路径: any, 文档新标题: any): Promise<any>;
declare function 删除思源文档(笔记本id: any, 文档路径: any): Promise<any>;
declare function 移动思源文档(源笔记本ID: any, 源路径: any, 目标笔记本ID: any, 目标路径: any): Promise<any>;
declare function 根据思源路径获取人类可读路径(笔记本ID: any, 路径: any): Promise<any>;
declare function 根据块ID查询文档人类可读完整路径(ID: any): Promise<any>;
declare function 通过markdown创建文档(notebook: any, path: any, markdown: any): Promise<any>;
declare function 列出指定路径下文档(路径: any): Promise<any>;
declare function 以id获取文档内容(id: any): Promise<any>;
declare function 以关键词搜索文档(k: any): Promise<any>;
export {};
